### ISSUE TITLE
Code Quality Enhancement

### ISSUE THREAD

**Issue by AliHaider20** [a96lex/pygame-floating-rocket#2]
The variable run working is to start and stop the while loop. It increaseses space complexity. Instead, you can use

    while True:
          if is_main_loop:
              points, pipe_gap, pipe_width, collided = main_loop(
              points, pipe_gap, pipe_width, clock_ticks
        )
         if collided:
            is_main_loop = False
    else:
        if points > highscore:
            highscore = points
        final_screen(points, highscore)
        key = pygame.key.get_pressed()

        if key[pygame.K_r]:
            clock_ticks = pygame.time.get_ticks()
            player, pipes, points, pipe_gap, pipe_width, pipe_speed = init_game()
            is_main_loop = True

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            break

**Comment by a96lex** [comment]
Thank you very much for your comments, I have added it. 

If you want to improve something else, feel free to fork the repo and send a pr :)
